### ISSUE TITLE
on beta when trying to register/login

### ISSUE THREAD

**Issue by karissa** [datproject/datproject.org#452]
```
{"time":"2017-02-16T18:10:01.602Z","hostname":"99f075a457eb","pid":17,"level":"info","name":"/usr/src/app/server/cli.js","message":"response","finished":true,"method":"GET","url":"/api/v1/dats?username=k","statusCode":200,"requestTime":8}
Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Error (native)
    at Sign.sign (crypto.js:283:26)
    at sign (/usr/src/app/node_modules/jwa/index.js:55:45)
    at Object.sign (/usr/src/app/node_modules/jwa/index.js:75:27)
    at Object.jwsSign [as sign] (/usr/src/app/node_modules/jws/lib/sign-stream.js:23:24)
    at Object.module.exports [as sign] (/usr/src/app/node_modules/jsonwebtoken/sign.js:146:16)
    at Object.sign (/usr/src/app/node_modules/township-token/index.js:74:16)
    at /usr/src/app/node_modules/township-accounts/index.js:135:25
    at /usr/src/app/node_modules/levelup/lib/levelup.js:230:7
```

**Comment by karissa** [comment]
I think this is fixed now by reading in the .pem keys from the filesystem, https://github.com/datproject/datproject.org/blob/master/example.config.js#L50-L53
